package me.ezar.anemon.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF88511D)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDCC2)
val onPrimaryContainerLight = Color(0xFF6C3A05)
val secondaryLight = Color(0xFF745944)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDCC2)
val onSecondaryContainerLight = Color(0xFF5A422E)
val tertiaryLight = Color(0xFF5C6237)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE0E7B1)
val onTertiaryContainerLight = Color(0xFF444A22)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF8F5)
val onBackgroundLight = Color(0xFF221A14)
val surfaceLight = Color(0xFFFFF8F5)
val onSurfaceLight = Color(0xFF221A14)
val surfaceVariantLight = Color(0xFFF3DFD2)
val onSurfaceVariantLight = Color(0xFF51443B)
val outlineLight = Color(0xFF847469)
val outlineVariantLight = Color(0xFFD6C3B6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF382F28)
val inverseOnSurfaceLight = Color(0xFFFEEEE4)
val inversePrimaryLight = Color(0xFFFFB77B)
val surfaceDimLight = Color(0xFFE7D7CD)
val surfaceBrightLight = Color(0xFFFFF8F5)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1E9)
val surfaceContainerLight = Color(0xFFFBEBE1)
val surfaceContainerHighLight = Color(0xFFF5E5DB)
val surfaceContainerHighestLight = Color(0xFFEFE0D6)